package edu.csh.chase.aggregations.exceptions

class ValueException : Exception() {
}